# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.smart-app-launch
canonical: http://hl7.org/fhir/smart-app-launch
name: SmartAppLaunch
title: "SMART App Launch"
status: active
version: 2.0.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Release #ci-build|draft|qa-preview|ballot|trial-use|release|update|normative+trial-use
date: '2021-10-30'
license: 'CC-BY-4.0'
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
publisher:
  name: HL7 International - FHIR Infrastructure WG
  url: https://hl7.org/Special/committees/fiwg
  email: fhir@lists.HL7.org
pages:
  index.md:
    title: Overview
  app-launch.md:
    title: 'App Launch: Launch and Authorization'
    example-app-launch-public.md:
      title: Example App Launch for Public Client
    example-app-launch-asymmetric-auth.md:
      title: Example App Launch for Asymmetric Client Auth
    example-app-launch-symmetric-auth.md:
      title: Example App Launch for Symmetric Client Auth
  scopes-and-launch-context.md:
    title: 'App Launch: Scopes and Launch Context'
    worked_example_id_token.md:
      title: Worked Example Id Token
  app-state.md:
    title: 'Persisting App State (Experimental)'
  backend-services.md:
    title: Backend Services
    example-backend-services.md:
      title: Example Backend Services Flow
  client-confidential-asymmetric.md:
    title: 'Client Authentication: Asymmetric (public key)'
    authorization-example-jwks-and-signatures.md:
      title: Example JWS generation for Asymmetric Client Auth
  client-confidential-symmetric.md:
    title: 'Client Authentication: Symmetric (shared secret)'
  token-introspection.md:
    title: Token Introspection
  conformance.md:
    title: Conformance
  best-practices.md:
    title: Best Practices
  examples.md:
    title: Examples
parameters:
  path-history: http://hl7.org/fhir/smart-app-launch/history.html
  jira-code: smart

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Overview of SMART on FHIR: index.html
  App Launch:
    Launch and Authorization: app-launch.html
    Scopes and Launch Context: scopes-and-launch-context.html
    Persisting App State: app-state.html
  Backend Services: backend-services.html
  Client Authentication:
    Asymmetric (public key): client-confidential-asymmetric.html
    Symmetric (shared secret): client-confidential-symmetric.html
  Token Introspection: token-introspection.html
  Conformance: conformance.html
  See also:
    #Artifacts: artifacts.html # no artifacts to display!
    Best Practices: best-practices.html
    Examples: examples.html
    History: http://hl7.org/fhir/smart-app-launch/history.html
